### PR TITLE
A set of improvements and fixes

### PR DESCRIPTION
**Pull request by dorileo**
Basically:
+ add visibility change callback
+ fix lixtbox selection event - also call the user callback whenever a selection is changed with keyboard
+ RemoveChild()/Destroy() interface

### CODE REVIEW

**Comment by VladimirMarkelov** [comment]
Good catches! Thank you.

A couple of questions:
1. What is a use case of Window.onVisible event? I ask because I cannot make up quickly a situation when I need it and I am not sure that firing event only when a Window gets visible is enough. I wonder: should we fire event on show/hide but use extra field of Event(maybe `X`?) to detect the Window on and off?

2. AddChild is 'internal' method(I marked it as internal because adding a new Control must rebuild all its parents that is not easy and needs some debugging and testing(maybe a new Event EventLayout called after adding a control helps). On the other hand, RemoveControl never increases the parent size and it works similar to SetVisible(false). It looks like the only advantage of RemoveControl is freeing allocated memory for the Control. Have you tried removing a Control that is a container with a few other Controls?
Why only Label has Destroy method? It seems the method should be BaseControl's one.

**Comment by dorileo** [comment]
1. a simple CRUD form (Create, read, update and delete), we can have a single form for both operations, in that case the onVisible event gives us the opportunity to change the form content accordingly. Other cases depending on data state should also apply. The show/hide alternative could be an option for the same problem.

2. I haven't tried using a container, I'm sure that for this case we'll need more work, that's the why I  included the Destroy() method only to Label.

For the Destroy() use case, it's not simply a matter of freeing memory, but you may eventually change your screen/window/form depending on the use interaction, imagine you have a single window and depending on the user interaction you add/remove labels to describe data the user manipulated. In that case you need to remove invalid labels and add new ones and so on. Take the case where you data display is not only limited to a ListBox, but you also have buttons and labels.

**Comment by dorileo** [comment]
I'm splitting this PR into fixes and topics.

**Comment by dorileo** [comment]
Fixes were moved to PR #88

**Comment by dorileo** [comment]
Window event was moved to PR #89

**Comment by dorileo** [comment]
Control destroy was moved to PR #90

**Comment by dorileo** [comment]
Now we can move discussions to their specific pull requests.

**Pull request closed without merging**
